# Generated by Django 4.2.4 on 2023-09-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_version_version_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_current_version',
            field=models.BooleanField(default=False, verbose_name='Текущая версия'),
        ),
    ]
