# Generated by Django 4.2.4 on 2023-09-13 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_version_is_current_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_edit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата последнего изменения'),
        ),
    ]
