# Generated by Django 4.2.4 on 2023-09-13 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_product_last_edit_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={},
        ),
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.product'),
        ),
    ]
